### ISSUE TITLE
Issues with 2002 Mr. Store

### ISSUE THREAD

**Issue by HiddenKnife526** [loathers/TourGuide#175]
When first logging into the game for the day, TourGuide shows 0 credits for the Catalog remaining, until one is spent, then it shows 3 remaining.

Additionally, clicking on the 2002 Mr. Store option in TourGuide loads up the Miscellaneous inventory with the message "You don't have the item you're trying to use." even though I have it and can use the item through other means.

**Comment by docrostov** [comment]
good catch on the second -- i never noticed this because i've only used the tile in Legacy of Loathing. it was linking to the replica store, not the normal store 😆 fixed with a conditional ID, will test out tomorrow and hopefully merge up

on the first, i unfortunately don't have a solution for it -- i have seen it before too, but tourguide is referencing base mafia preferences, so this reflects mafia prefs not updating until you visit/spend. kind of a pain. i probably should dig into the java on how that pref is instantiated and see if i can tell ryo or rinn about it lol

**Comment by docrostov** [comment]
addressed in #176 which is now in main. thanks for the report!
