### ISSUE TITLE
support for Fall of the Dinosaurs 🦖

### ISSUE THREAD

**Issue by docrostov** [loathers/TourGuide#71]
this is a thread for general support for the Fall of the Dinosaurs (called 🦖 going forward) special challenge path. will add things here that would be good for tourguide to display for users.

- in 🦖, you do not need to get the boning knife if you get a birdseed hat -- this turns monsters into chicken-consumed creatures, and reduces the wall of bones' HP to 1, which makes towerkilling incredible simple. this is a reasonable use of dinodollars i think. 
- similarly, if you have a birdseed hat, in 🦖 you don't really need to worry about smut orcs at all, because you only need 5 friggin cold damage to beat them to max your blech house progress. nice.
- tab within resources for dinodollars (and specifically recommending to buy the birdseed hat + repellant, for freerun purposes)

add things here if there are differences in 🦖 that would be helpful for tourguide to track

**Comment by JamesDowney** [comment]
Noting the dino defecation zone and the delay left in that zone would be helpful, as well as probably noting research and dino parts needed until the next dino buck payout.

**Comment by wRAR** [comment]
Acquiring dinodollars (these need Mafia support first I guess):
* The current location with droppings
* The current progress of the trophies quest
* (the most important) the current progress of the research quest, as you can't get excess points

Remove the wand hints.

The palindome dino seems to be immune to weapons and spells, so add a hint for that.

**Comment by docrostov** [comment]
additional note: in 🦖, the chicken hat reduces meatgain to 0. prior to nuns, probably need to banish chickens w/ the freerun dino banish and use pheromones on kachungasaurs.

**Comment by Thoth19** [comment]
The only thing I can think of that hasn't been said above is maybe something about reminding to use repellents in a resources tab?
Oh re chicken hat for smorcs, banishing the arcosaur is also potentially a good idea here instead or in addition to.
Another one might be that if you banish chickens, the chicken hat cannot summon them, so that might also be a cute reminder if you have banished them and have the hat equipped

But IMO the most important for me is the dino-poop related ones. Second most would be the trackers for research (combat text will tell you if you pay attn) and dino bits (less important bc you can overcap without losing things)

Smorcs andor tower test might want to say to use dinoade if you have it?

**Comment by docrostov** [comment]
closing this issue because i added a small amount of dino support with everything that was mafia tracked, but mafia tracking never got powerful enough to do a few extra things. alas.
