### ISSUE TITLE
Add Warbear induction oven

### ISSUE THREAD

**Issue by boppreh** [loathers/TourGuide#85]
With a [Warbear Induction Oven](https://kol.coldfront.net/thekolwiki/index.php/Warbear_induction_oven) in the workshed, the first food you cook after rollover is duplicated. If the player hasn't cooked anything today yet, making a digital key lime for example is an easy 25k profit.

**Comment by docrostov** [comment]
this would've been nice prior to the workshed nerf but now i think it's probably fine to ignore as this is purely an aftercore thing; since you can't have the induction oven without a pull this feels like a weird/bad use of pulls we don't need to support. sorry bud. thank you for the suggestion. if you would like to re-request it please let me know here or post in #tourguide in the ASS discord that you'd still like this and see if zinc or beldur or me is feelin' spicy.
